services:
  app:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - ../:/workspace/
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
